# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76afd53184bbe7e7ce0b675556645f63caf734f91b658bb23cd3bbb7a911f27bd6c840c6a3f8ee82ac219e3ab0616be5203b1eb0d41cbd8b93bd48703f23b265

test:
  secret_key_base: d9d365f068b6f37cdb9bcf755582788c80be6efb5e78be001e3aa12d00d0f1df83a719b703932df355f3ea30cc6f2ca24d350f304c42346d8c5b9ee1c864dabd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
